name: Sync to New Frontend Repo

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "campus-ua"
          git config user.email "campusdev2021@gmail.com"

      - name: Commit and push
        run: |
          git add -A
          git commit -m "Sync from original repo" || echo "No changes to commit"
          git remote add ler-sem-fronteiras-deployed https://github.com/campus-ua/ler-sem-fronteiras-deployed.git
          git push ler-sem-fronteiras-deployed HEAD:main --force

      - name: Trigger SerMais CI/CD in ler-sem-fronteiras-deployed repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: campus-ua/ler-sem-fronteiras-deployed
          event-type: sync-completed
